sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 8
addons:
  chrome: stable
script:
  - ./node_modules/.bin/ng test --code-coverage --no-progress --browsers=ChromeHeadless
after_success:
  - yarn ghpages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $GITHUB_TOKEN
  on:
    branch: master
